---
- name: Install global dependencies into the virtualenv
  pip: virtualenv={{ base_path }}/pari_env name={{ item }} state=forcereinstall
  with_items:
    - pip
    - six
    - setuptools
    - gunicorn
    - ipython
    - hiredis
    - redis
  tags:
    - install

#- name: Create the virtualenv
#  command: virtualenv --distribute {{ base_path }}/pari_env
#  tags: install

- name: Clone the source from github
  git: clone=yes accept_hostkey=yes repo={{ git_repo }} dest={{ app_path }}
  tags: install

- name: Pull the latest code
  git: repo={{ git_repo }} update=yes dest={{ app_path }} version={{ git_revision_to_pull }}
  tags: deploy

- name: Copy the local.py file
  template: src=local.py dest={{ app_path }}/pari/settings/local.py
  tags: deploy
  ignore_errors: true

- name: Install dependencies from requirements.txt
  pip: requirements={{ requirements_file }} virtualenv={{ base_path }}/pari_env
  tags:
    - install
    - deploy

- name: manage.py migrate
  django_manage: >
    command=migrate
    virtualenv={{ base_path }}/pari_env
    app_path={{ app_path }}
    settings={{ settings_path }}
  tags:
    - install
    - deploy

- name: Copy the supervisor.conf
  template: src=supervisord.conf dest=/etc/supervisor/conf.d/pari.conf
  become: true
  become_method: sudo
  tags: install

- name: Copy the gunicorn_conf.py to the project
  template: src=gunicorn_conf.py dest={{ app_path }}/gunicorn_conf.py
  tags: install

- name: Copy the crontab
  template: src=crontab dest=/etc/cron.d/ubuntu
  become: true
  become_method: sudo
  tags:
    - install
    - deploy

- name: Create the scripts directory
  file: state=directory path={{ base_path }}/scripts
  tags:
    - install
    - deploy
  ignore_errors: true

- name: Copy the publish_scheduled_pages.sh script
  template: src=publish_scheduled_pages.sh dest={{ base_path }}/scripts/publish_scheduled_pages.sh mode=0755
  tags:
    - install
    - deploy

- name: Copy the db_backup.sh script
  template: src=db_backup.sh dest={{ base_path }}/scripts/db_backup.sh mode=0755
  tags:
    - install
    - deploy

- name: Collectstatic
  django_manage: >
    command="collectstatic --noinput"
    virtualenv={{ base_path }}/pari_env
    app_path={{ app_path }}
    settings={{ settings_path }}
  tags:
    - install
    - deploy

- name: Compress media
  django_manage: >
    command="compress"
    virtualenv={{ base_path }}/pari_env
    app_path={{ app_path }}
    settings={{ settings_path }}
  tags:
    - install
    - deploy
  ignore_errors: true

- name: Update search index
  django_manage: >
    command="update_index"
    virtualenv={{ base_path }}/pari_env
    app_path={{ app_path }}
    settings={{ settings_path }}
  tags:
    - install
    - deploy
  ignore_errors: true

- name: Clear cache
  redis: command=flush flush_mode=all
  tags:
    - install
    - deploy
  ignore_errors: true

- name: Restart supervisord
  command: service supervisor restart
  become: true
  become_method: sudo
  tags: install

- name: Restart gunicorn through supervisor
  supervisorctl: name={{ proj_name }}:gunicorn_{{ proj_name }} state=restarted
  become: true
  become_method: sudo
  tags:
    - install
    - deploy
