---
- name: Install postgres
  apt: name={{ item }}
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
  become: true
  become_method: sudo
  tags: install

- name: Install postgis
  apt: name={{ item }}
  with_items:
    - binutils
    - libproj-dev
    - gdal-bin
    - postgresql-9.3-postgis-2.1
    - postgresql-9.3-postgis-scripts
  become: true
  become_method: sudo
  tags: install

- name: Create a db user
  postgresql_user: name={{ db_user }} password={{ db_password }}
  vars:
    ansible_ssh_pipelining: true
  become: true
  become_method: sudo
  become_user: postgres
  tags: install

- name: Create a db
  postgresql_db: name={{ db_name }} owner={{ db_user }}
  vars:
    ansible_ssh_pipelining: true
  become: true
  become_method: sudo
  become_user: postgres
  tags: install

- name: Create the PostGIS extension
  postgresql_ext: name=postgis db={{ db_name }}
  vars:
    ansible_ssh_pipelining: true
  become: true
  become_method: sudo
  become_user: postgres
  tags: install

- name: Development setup
  include: development_setup.yml
  when: is_local_development
  tags: install